version: "3.8"

services:
  web01:
    image: felipealcantara/rinha-de-backend-2024:latest
    environment:
      GIN_MODE: release
      APP_IN_MEMORY: "false"
    expose:
    - "8080"
    depends_on:
    - db
    deploy:
      resources:
        limits:
          cpus: "0.27"
          memory: "60MB"
  web02:
    image: felipealcantara/rinha-de-backend-2024:latest
    environment:
      GIN_MODE: release
      APP_IN_MEMORY: "false"
    expose:
    - "8080"
    depends_on:
    - db
    deploy:
      resources:
        limits:
          cpus: "0.27"
          memory: "60MB"

  lb:
    image: felipealcantara/rinha-de-backend-2024-lb:latest
    ports:
    - "9999:9999"
    depends_on:
    - web01
    - web02
    deploy:
      resources:
        limits:
          cpus: "0.27"
          memory: "60MB"

  db:
    image: mongo:7.0.5
    expose:
    - "27017"
    deploy:
      resources:
        limits:
          cpus: "0.57"
          memory: "370MB"