FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build loadbalancer/load_balancer.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/load_balancer .
RUN chmod +x load_balancer
EXPOSE 9090
CMD ["./load_balancer"]
